export enum MudEvents {
    NONE = -1,
    DUPLICATE_NAME = 0,
    EVENT = 1,
    WELCOME = 2,
    ERROR = 3,
    INFO = 4,
    ROOM = 5,
    COMMAND = 6,
    USERNAME_REQUEST = 7,
    USERNAME_ANSWER = 8,
    BOOK = 9,
    TIME = 10,
    CHANGE_NAME = 11,
    YOU_ATTACK = 12,
    INVENTORY = 13,
    ATTACK = 14,
    HEALTH = 15,
    CLIENT_LIST = 16,
    MAP_EVENT = 17,
    ROOM_IMAGE = 18,
    DIRECTION = 19,
    ANNOUCEMENT = 20,
    ENVIRONMENT = 21,

}